version: '3'

services:
  # 订阅合并服务
  subscription-service:
    build: .
    container_name: subscription-service
    ports:
      - "25500:25500"  # 订阅服务端口
    volumes:
      - subscription_config:/opt/sub_merger  # 订阅配置持久存储
      - subscription_logs:/var/log           # 订阅日志持久存储
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN:-your_access_token_here}  # 访问令牌
      - PORT=25500                           # 服务端口
    restart: always
    networks:
      - subscription_network

volumes:
  subscription_config:
  subscription_logs:

networks:
  subscription_network:
    driver: bridge